/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Confirmation
         * @description Një lidhje e re për një llogari të pakonfirmuar. Përgjigja është e njëjtë me atë të regjistrimit.
         */
        post: operations["resend_confirmation_auth_resend_confirmation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Kërkon lidhjen për të vendosur fjalëkalim të ri (ADR 0018). Përgjigja është e njëjtë për çdo email.
         *
         *     Një llogari e konfirmuar merr lidhjen e rivendosjes. Një e pakonfirmuar merr lidhjen e konfirmimit, jo atë të
         *     rivendosjes: rivendosja nuk duhet të jetë rrugë anash konfirmimit. Një email pa llogari nuk merr asgjë.
         */
        post: operations["forgot_password_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Vendos fjalëkalimin e ri me tokenin e lidhjes (ADR 0018).
         *
         *     Vlen një herë dhe skadon. Një token i panjohur, i përdorur ose i skaduar kthen të njëjtën gabim. Fjalëkalimi
         *     i ri hash-ohet para se tokeni të kontrollohet, që koha të mos tregojë nëse tokeni ishte i vlefshëm. Pas suksesit
         *     çdo seancë e përdoruesit revokohet; hapi i dytë, nëse ka, mbetet i paprekur (një kuti postare e vjedhur nuk
         *     e kalon).
         */
        post: operations["reset_password_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm
         * @description Konfirmon email-in me tokenin e lidhjes. Vlen një herë; një token i panjohur, i përdorur ose i
         *     skaduar kthen të njëjtën gabim.
         */
        post: operations["confirm_auth_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokon seancën: tokenët e aksesit dhe të rifreskimit pushojnë menjëherë.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout All
         * @description Dil kudo: revokon çdo seancë të hapur të përdoruesit, edhe këtë, menjëherë.
         */
        post: operations["logout_all_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_auth_2fa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll
         * @description Nis regjistrimin: një sekret i ri, i dukshëm vetëm në këtë përgjigje. Thirrja e dytë para konfirmimit e
         *     zëvendëson sekretin; pasi hapi i dytë aktivizohet, kjo pikë kthen 409 dhe sekreti nuk lexohet më.
         */
        post: operations["enroll_auth_2fa_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm
         * @description Aktivizon hapin e dytë me kodin e parë të vlefshëm dhe kthen kodet e rimëkëmbjes, një herë.
         */
        post: operations["confirm_auth_2fa_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable
         * @description Çaktivizon hapin e dytë. Kërkon fjalëkalimin e tanishëm dhe një kod (aplikacioni ose rimëkëmbjeje): një token
         *     aksesi i vjedhur vetëm nuk mjafton. Gabimet kufizohen si te hyrja.
         */
        post: operations["disable_auth_2fa_disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Login
         * @description Hapi i dytë i hyrjes: sfida nga `login` dhe një kod. Hap seancën kur kodi vlen.
         */
        post: operations["verify_login_auth_login_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_documents_get"];
        put?: never;
        /** Upload */
        post: operations["upload_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Remove */
        delete: operations["remove_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_documents__document_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pages */
        get: operations["pages_documents__document_id__pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/pages/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Page Image */
        get: operations["page_image_documents__document_id__pages__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Findings */
        get: operations["findings_documents__document_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/assertions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assertions */
        get: operations["assertions_documents__document_id__assertions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/cross-refs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross Refs */
        get: operations["cross_refs_documents__document_id__cross_refs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explanation */
        get: operations["explanation_documents__document_id__explanation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verification */
        get: operations["verification_documents__document_id__verification_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terminology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Glossary */
        get: operations["glossary_terminology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terminology/{term}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup */
        get: operations["lookup_terminology__term__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat */
        get: operations["chat_documents__document_id__chat_get"];
        put?: never;
        /** Chat */
        post: operations["chat_documents__document_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/privacy/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Privacy Config */
        get: operations["privacy_config_privacy_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Erase Account
         * @description Fshin llogarinë dhe çdo dokument të saj, pas verifikimit të fjalëkalimit.
         *
         *     Pas kësaj tokenët e pronarit nuk vlejnë më (seancat shkojnë me llogarinë), prandaj një përsëritje e së njëjtës kërkesë
         *     kthen 401, jo një gabim tjetër. Fjalëkalimi i gabuar kthen 403 dhe jo 401, që klienti të mos e marrë për seancë të
         *     skaduar dhe të nisë një rifreskim.
         */
        delete: operations["erase_account_me_data_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyteFinding
         * @description Një vlerë laboratorike e nxjerrë, e normalizuar dhe e klasifikuar.
         *
         *     Ruhen si vlera e papërpunuar (ashtu si është shtypur) ashtu edhe ajo
         *     e normalizuar. E para nevojitet për auditim dhe për vlerësimin e
         *     PK1; e dyta për klasifikim dhe verifikim.
         */
        AnalyteFinding: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Analyte Code
             * @description Kodi LOINC
             */
            analyte_code: string;
            /**
             * Analyte Name Raw
             * @description Emri ashtu si është shtypur
             */
            analyte_name_raw: string;
            /** Analyte Name Canonical */
            analyte_name_canonical: string;
            /**
             * Value Raw
             * @description Teksti origjinal, p.sh. '0,95'
             */
            value_raw: string;
            /** Value */
            value: string;
            /** Unit Raw */
            unit_raw?: string | null;
            /** Unit Canonical */
            unit_canonical: string;
            /**
             * Value Canonical
             * @description Pas konvertimit të njësisë
             */
            value_canonical: string;
            /** Ref Low */
            ref_low?: string | null;
            /** Ref High */
            ref_high?: string | null;
            ref_source: components["schemas"]["ReferenceSource"];
            status: components["schemas"]["AnalyteStatus"];
            /**
             * Severity
             * @description Largësia nga kufiri i intervalit pjesëtuar me gjerësinë e intervalit. None kur statusi është NORMAL ose UNINTERPRETABLE.
             */
            severity?: string | null;
            /** Page */
            page: number;
            bbox?: components["schemas"]["BoundingBox"] | null;
            /** Measured At */
            measured_at?: string | null;
            /**
             * Flag In Document
             * @description Flamuri i shtypur nga laboratori: H, L, *, ↑
             */
            flag_in_document?: string | null;
        };
        /**
         * AnalyteStatus
         * @description Klasifikimi i një vlere kundrejt intervalit referent.
         *
         *     UNINTERPRETABLE nuk është gabim: ai shënon rastin kur nuk u gjet
         *     asnjë interval referent. Politika e sigurisë SP5 kërkon që sistemi
         *     të refuzojë interpretimin në këtë rast në vend që të hamendësojë.
         * @enum {string}
         */
        AnalyteStatus: "critical_low" | "low" | "normal" | "high" | "critical_high" | "uninterpretable";
        /**
         * AssertionKind
         * @description Çfarë lloj pohimi është nxjerrë nga narrativa.
         * @enum {string}
         */
        AssertionKind: "finding" | "recommendation" | "term_mention";
        /** AttemptOut */
        AttemptOut: {
            /** Attempt */
            attempt: number;
            /** Generator */
            generator: string;
            /** Is Fallback */
            is_fallback: boolean;
            /** Delivered */
            delivered: boolean;
            /** Failed */
            failed: boolean;
            verification: components["schemas"]["VerificationDetail"] | null;
        };
        /** Body_upload_documents_post */
        Body_upload_documents_post: {
            /** File */
            file: string;
            /**
             * Model Consent
             * @default false
             */
            model_consent: boolean;
        };
        /**
         * BoundingBox
         * @description Pozicioni i një elementi në faqe, në pikë PDF.
         *
         *     Ruhet që ndërfaqja të mund të theksojë zonën burimore të një vlere.
         *     Është e lirë për t'u ruajtur tani dhe e shtrenjtë për t'u shtuar më vonë.
         */
        BoundingBox: {
            /** X0 */
            x0: number;
            /** Y0 */
            y0: number;
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
        };
        /**
         * Certainty
         * @description Niveli i sigurisë i shprehur nga mjeku.
         *
         *     HEDGED mbulon "e mundshme", "sugjeruese për", "nuk përjashtohet".
         *     Heqja e këtij niveli në thjeshtim është shkelje (rregulli R6).
         * @enum {string}
         */
        Certainty: "confirmed" | "hedged";
        /** CodeIn */
        CodeIn: {
            /** Code */
            code: string;
        };
        /** ConfirmIn */
        ConfirmIn: {
            /** Token */
            token: string;
        };
        /** Credentials */
        Credentials: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * CrossReference
         * @description Rezultati i krahasimit ndërmjet një pohimi dhe një gjetjeje.
         */
        CrossReference: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Analyte Code */
            analyte_code: string;
            state: components["schemas"]["CrossReferenceState"];
            /** Assertion Id */
            assertion_id?: string | null;
            /** Finding Id */
            finding_id?: string | null;
        };
        /**
         * CrossReferenceState
         * @description Rezultati i krahasimit raport ↔ laborator.
         *
         *     MEASURED_NOT_MENTIONED zbulon mungesa dhe jo gabime; është kategoria
         *     më e vështirë për t'u vërejtur nga një lexues njerëzor.
         * @enum {string}
         */
        CrossReferenceState: "agreement" | "contradiction" | "mentioned_not_measured" | "measured_not_mentioned";
        /**
         * Direction
         * @description Drejtimi i shprehur për një analit, në gjetje ose në pohim.
         * @enum {string}
         */
        Direction: "increased" | "decreased" | "normal" | "unspecified";
        /** DisableTwoFactorIn */
        DisableTwoFactorIn: {
            /** Password */
            password: string;
            /** Code */
            code: string;
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Size Bytes */
            size_bytes: number;
            /** State */
            state: string;
            /** State Reason */
            state_reason: string;
            /** Channel */
            channel: string | null;
            /** Terminal */
            terminal: boolean;
            /** Model Consent */
            model_consent: boolean;
        };
        /** DocumentPage */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["DocumentOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** EmailIn */
        EmailIn: {
            /** Email */
            email: string;
        };
        /** ErasureIn */
        ErasureIn: {
            /** Password */
            password: string;
        };
        /** ExplanationOut */
        ExplanationOut: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Text */
            text: string;
            /** Generator */
            generator: string;
            /** Critical */
            critical: boolean;
            /** Banner */
            banner: string | null;
            /** Disclaimer */
            disclaimer: string;
            /** Notices */
            notices: components["schemas"]["Notice"][];
            verification: components["schemas"]["VerificationSummary"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobOut */
        JobOut: {
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Failed */
            failed: boolean;
        };
        /** LoginVerifyIn */
        LoginVerifyIn: {
            /** Challenge */
            challenge: string;
            /** Code */
            code: string;
        };
        /**
         * MfaChallenge
         * @description Përgjigjja e hyrjes kur llogaria ka hap të dytë: fjalëkalimi ishte i saktë, por seanca hapet vetëm pas
         *     kodit (`POST /auth/login/verify`). Del vetëm pas fjalëkalimit të saktë, prandaj nuk tregon gjë për
         *     llogaritë e tjera (ADR 0018).
         */
        MfaChallenge: {
            /**
             * Mfa Required
             * @default true
             * @constant
             */
            mfa_required: true;
            /** Challenge */
            challenge: string;
        };
        /**
         * Notice
         * @description Një kufizim i shprehur nga sistemi. `code` e lejon ndërfaqen ta vendosë
         *     aty ku duhet — njoftimi i OCR-së në krye, jo i humbur në fund.
         */
        Notice: {
            /** Code */
            code: string;
            /** Text */
            text: string;
        };
        /** PagesOut */
        PagesOut: {
            /** Count */
            count: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /**
         * Polarity
         * @description Pohim ose mohim. NegEx-i vendos këtë fushë.
         * @enum {string}
         */
        Polarity: "affirmed" | "negated";
        /** PrivacyConfig */
        PrivacyConfig: {
            /** Model Enabled */
            model_enabled: boolean;
            /** Model Provider */
            model_provider: string | null;
            /** Retention Days */
            retention_days: number;
        };
        /**
         * RecoveryCodes
         * @description Kodet e rimëkëmbjes. Shfaqen vetëm një herë: shërbimi mban vetëm HMAC-in e tyre.
         */
        RecoveryCodes: {
            /** Recovery Codes */
            recovery_codes: string[];
        };
        /**
         * ReferenceSource
         * @description Nga erdhi intervali referent i përdorur për klasifikim.
         *
         *     Raportohet në rezultatet e PK2: përpjesa e vlerave të klasifikuara
         *     me interval nga dokumenti kundrejt tabelës së brendshme është
         *     tregues i cilësisë së nxjerrjes.
         * @enum {string}
         */
        ReferenceSource: "document" | "internal_table" | "none";
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RegisterOut
         * @description Përgjigjja e regjistrimit dhe e ridërgimit: e njëjtë për çdo email, që të mos tregojë
         *     nëse ai ka llogari (ADR 0016).
         */
        RegisterOut: {
            /** Message */
            message: string;
        };
        /**
         * ReportAssertion
         * @description Një pohim i nxjerrë nga teksti narrativ i mjekut.
         *
         *     char_start/char_end lejojnë gjurmimin prapa te teksti origjinal, i
         *     nevojshëm si për auditim ashtu edhe për anotimin manual gjatë
         *     vlerësimit të PK4.
         */
        ReportAssertion: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Text Span */
            text_span: string;
            /**
             * Analyte Code
             * @description None kur pohimi nuk lidhet me një analit të matshëm
             */
            analyte_code?: string | null;
            direction: components["schemas"]["Direction"];
            polarity: components["schemas"]["Polarity"];
            certainty: components["schemas"]["Certainty"];
            kind: components["schemas"]["AssertionKind"];
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
        };
        /** ResetIn */
        ResetIn: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** StatusOut */
        StatusOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** State */
            state: string;
            /** Reason */
            reason: string;
            /** Terminal */
            terminal: boolean;
            job: components["schemas"]["JobOut"] | null;
            /** Transitions */
            transitions: components["schemas"]["TransitionOut"][];
        };
        /** TermOut */
        TermOut: {
            /** Term */
            term: string;
            /** Explanation Sq */
            explanation_sq: string;
            /** Category */
            category: string | null;
            /** Synonyms */
            synonyms: string[];
            /** Source Ref */
            source_ref: string;
        };
        /** Tokens */
        Tokens: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TransitionOut */
        TransitionOut: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Reason */
            reason: string;
            /** Attempt */
            attempt: number | null;
            /** At */
            at: string;
        };
        /**
         * TwoFactorEnrollment
         * @description Sekreti dhe URI-ja e aplikacionit. Shfaqen vetëm këtu, një herë; pasi regjistrimi të konfirmohet nuk lexohen më.
         */
        TwoFactorEnrollment: {
            /** Secret */
            secret: string;
            /** Otpauth Uri */
            otpauth_uri: string;
        };
        /** TwoFactorStatus */
        TwoFactorStatus: {
            /** Enabled */
            enabled: boolean;
            /** Recovery Codes Remaining */
            recovery_codes_remaining: number;
        };
        /** UploadOut */
        UploadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** State */
            state: string;
            /** Model Consent */
            model_consent: boolean;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationDetail */
        VerificationDetail: {
            /** Passed */
            passed: boolean;
            /** Mode */
            mode: string;
            /** Rules Version */
            rules_version: string;
            /** Classifier Version */
            classifier_version: string | null;
            /** Duration Ms */
            duration_ms: number;
            /** Violations */
            violations: components["schemas"]["ViolationOut"][];
        };
        /** VerificationOut */
        VerificationOut: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            verification: components["schemas"]["VerificationSummary"];
            /** Attempts */
            attempts: components["schemas"]["AttemptOut"][];
        };
        /** VerificationSummary */
        VerificationSummary: {
            /** Passed */
            passed: boolean;
            /** Mode */
            mode: string;
            /** Violation Count */
            violation_count: number;
            /** Is Fallback */
            is_fallback: boolean;
        };
        /** ViolationOut */
        ViolationOut: {
            /** Type */
            type: string;
            /** Detected By */
            detected_by: string;
            /** Sentence */
            sentence: string;
            /** Evidence */
            evidence: string;
            /** Confidence */
            confidence: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_confirmation_auth_resend_confirmation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_auth_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tokens"] | components["schemas"]["MfaChallenge"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tokens"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_all_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    status_auth_2fa_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoFactorStatus"];
                };
            };
        };
    };
    enroll_auth_2fa_enroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoFactorEnrollment"];
                };
            };
        };
    };
    confirm_auth_2fa_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_auth_2fa_disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisableTwoFactorIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_login_auth_login_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginVerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tokens"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_documents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_documents__document_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pages_documents__document_id__pages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_image_documents__document_id__pages__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                number: number;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/png": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_documents__document_id__findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyteFinding"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assertions_documents__document_id__assertions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportAssertion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cross_refs_documents__document_id__cross_refs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossReference"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explanation_documents__document_id__explanation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verification_documents__document_id__verification_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    glossary_terminology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"][];
                };
            };
        };
    };
    lookup_terminology__term__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_documents__document_id__chat_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_documents__document_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    privacy_config_privacy_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyConfig"];
                };
            };
        };
    };
    erase_account_me_data_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ErasureIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
