"""skema fillestare

Rishikimi: 0001
Paraardhësi: 
Krijuar: 2026-09-28 22:14:51.307797
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_document_created', 'audit_events', ['document_id', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filename_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('state_reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('cross_references',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('analyte_code', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('assertion_id', sa.Uuid(), nullable=True),
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_references_document_id'), 'cross_references', ['document_id'], unique=False)
    op.create_table('document_glossary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('explanation_sq', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_glossary_document_id'), 'document_glossary', ['document_id'], unique=False)
    op.create_table('document_unexplained_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_unexplained_terms_document_id'), 'document_unexplained_terms', ['document_id'], unique=False)
    op.create_table('explanations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('generator', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('final_output', sa.Text(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanations_document_id'), 'explanations', ['document_id'], unique=False)
    op.create_table('lab_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('analyte_code', sa.String(length=20), nullable=False),
    sa.Column('analyte_name_raw', sa.String(length=200), nullable=False),
    sa.Column('analyte_name_canonical', sa.String(length=200), nullable=False),
    sa.Column('value_raw', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('unit_raw', sa.String(length=40), nullable=True),
    sa.Column('unit_canonical', sa.String(length=40), nullable=False),
    sa.Column('value_canonical', sa.String(length=64), nullable=False),
    sa.Column('ref_low', sa.String(length=64), nullable=True),
    sa.Column('ref_high', sa.String(length=64), nullable=True),
    sa.Column('ref_source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=64), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('measured_at', sa.Date(), nullable=True),
    sa.Column('flag_in_document', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lab_findings_document_analyte', 'lab_findings', ['document_id', 'analyte_code'], unique=False)
    op.create_table('pattern_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.String(length=20), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_observations_document_id'), 'pattern_observations', ['document_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=False)
    op.create_table('report_assertions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text_span', sa.Text(), nullable=False),
    sa.Column('analyte_code', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('polarity', sa.String(length=20), nullable=False),
    sa.Column('certainty', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_assertions_document_id'), 'report_assertions', ['document_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('explanation_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('rules_version', sa.String(length=20), nullable=False),
    sa.Column('classifier_version', sa.String(length=200), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['explanation_id'], ['explanations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('explanation_id')
    )
    op.create_table('violations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_result_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('detected_by', sa.String(length=20), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['verification_result_id'], ['verification_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_verification_result_id'), 'violations', ['verification_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_verification_result_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_report_assertions_document_id'), table_name='report_assertions')
    op.drop_table('report_assertions')
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_pattern_observations_document_id'), table_name='pattern_observations')
    op.drop_table('pattern_observations')
    op.drop_index('ix_lab_findings_document_analyte', table_name='lab_findings')
    op.drop_table('lab_findings')
    op.drop_index(op.f('ix_explanations_document_id'), table_name='explanations')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_document_unexplained_terms_document_id'), table_name='document_unexplained_terms')
    op.drop_table('document_unexplained_terms')
    op.drop_index(op.f('ix_document_glossary_document_id'), table_name='document_glossary')
    op.drop_table('document_glossary')
    op.drop_index(op.f('ix_cross_references_document_id'), table_name='cross_references')
    op.drop_table('cross_references')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_audit_events_document_created', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
